// <auto-generated />
using System;
using Contactos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contactos.Migrations
{
    [DbContext(typeof(ContactosContext))]
    [Migration("20230416231357_Primer Migracion")]
    partial class PrimerMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Contactos.Entities.Contacto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NroDocumento")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contactos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Apellido = "Santos",
                            Nombre = "Mario",
                            NroDocumento = 12345678L,
                            TipoDocumento = "DNI"
                        },
                        new
                        {
                            Id = 2L,
                            Apellido = "Ravenna",
                            Nombre = "Emilio",
                            NroDocumento = 23456789L,
                            TipoDocumento = "DNI"
                        });
                });

            modelBuilder.Entity("Contactos.Entities.Telefono", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("ContactosId")
                        .HasColumnType("bigint");

                    b.Property<long>("NroTelefono")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactosId");

                    b.ToTable("Telefonos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ContactosId = 1L,
                            NroTelefono = 1566778899L,
                            TipoTelefono = "Movil"
                        },
                        new
                        {
                            Id = 2L,
                            ContactosId = 1L,
                            NroTelefono = 1599887766L,
                            TipoTelefono = "Movil"
                        },
                        new
                        {
                            Id = 3L,
                            ContactosId = 2L,
                            NroTelefono = 1599887766L,
                            TipoTelefono = "Movil"
                        });
                });

            modelBuilder.Entity("Contactos.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Password = "Password",
                            Usuario1 = "Admin"
                        });
                });

            modelBuilder.Entity("Contactos.Entities.Telefono", b =>
                {
                    b.HasOne("Contactos.Entities.Contacto", "Contactos")
                        .WithMany("Telefonos")
                        .HasForeignKey("ContactosId");

                    b.Navigation("Contactos");
                });

            modelBuilder.Entity("Contactos.Entities.Contacto", b =>
                {
                    b.Navigation("Telefonos");
                });
#pragma warning restore 612, 618
        }
    }
}
